### ISSUE TITLE
AWS RDS, Aurora cloudwatch collection error

### ISSUE THREAD

**Issue by cartum** [rapidloop/pgmetrics#43]
Hi!
I´m trying to run pgmetrics from linux to get the metrics for RDS Aurora Cluster and I´m getting this error:

`pgmetrics: warning: failed to collect from AWS RDS: failed to get CloudWatch metric data: ValidationError: The value idEBSIOBalance% for parameter MetricDataQueries.member.30.Id is not matching the expected pattern ^[a-z][a-zA-Z0-9_]*$.
The value idEBSByteBalance% for parameter MetricDataQueries.member.31.Id is not matching the expected pattern ^[a-z][a-zA-Z0-9_]*$.
        status code: 400, request id: 72bfee0a-a37f-4c4b-aa88-a5a304b4b660`

The command that we are running is:

`PGPASSWORD=XXXXXXXX ./pgmetrics -h writer-instance-endpoint -U SuperUser --aws-rds-dbid=clstr-instance-identifier -w -fjson database`	

The database output is ok, just fail with the RDS stats.

Thanks very much!

**Comment by mdevan** [comment]
Thanks for reporting. Is this a regular RDS or Aurora? What type of EBS volume does it have?

**Comment by cartum** [comment]
It's an Aurora cluster provisioned with IOPS SSD (io1).

**Comment by mdevan** [comment]
Fixed in e928d42.

To test, you'll have to build from master:
1. If you do not have Go installed, [install it first](https://golang.org/doc/install)
2. Run `cd $(mktemp -d) && go get github.com/rapidloop/pgmetrics/cmd/pgmetrics@master`
3. New pgmetrics binary will be in `~/go/bin`

Feel free to reopen the issue if problem persists.
