### ISSUE TITLE
pg_stat(io)_user_tables query failed: ERROR: canceling statement due to lock timeout (SQLSTATE 55P03)

### ISSUE THREAD

**Issue by naveenjul29** [rapidloop/pgmetrics#71]
I executed the below command and got the error:

pgmetrics -t 180 -h <<azure server name>> -p 5432 -U <<username>> --az-resource <<azure resource>> -o <<outputfile>> <<dbname>>

**Error:**
pg_stat(io)_user_tables query failed: ERROR: canceling statement due to lock timeout (SQLSTATE 55P03)

**Comment by mdevan** [comment]
pgmetrics is designed to fail to collect metrics rather than interfere with other ongoing queries, so such errors are not unexpected.

Try setting a higher value for lock timeout using `--lock-timeout` option. Note that this is in milliseconds. An option of `--lock-timeout=5000` gives 5 seconds lock timeout.

Also try running at a different time, when fewer operations/queries are going on. If pgmetrics is being run regularly, ignore occasional failures due this reason.
